apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: chatty-app
    image: chatty-app
    imagePullPolicy: Never      
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: nxlog-ce
    image: nxlog/nxlog-ce
    args: ["-c", "/etc/nxlog/nxlog.conf"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: config
      mountPath: /etc/nxlog
  volumes:
  - name: varlog
    emptyDir: {}
  - name: config
    configMap:
      name: nxlog-configmap