apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: chatty-app
    image: chatty-app      
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: fluentbit-agent
    image: fluent/fluent-bit
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: config
      mountPath: /fluent-bit/etc
  volumes:
  - name: varlog
    emptyDir: {}
  - name: config
    configMap:
      name: fluentbit-configmap